version: '3'

services:

  front:
    image: node:14.10.1
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/var/www/front
    working_dir: /var/www/front
    command: yarn start
    tty: true
    networks:
      - tienda-d-web

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ../backend:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend 
      - mysql
    networks:
      - tienda-d-web

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /var/lib/mysql
    networks:
      - tienda-d-db

  backend:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ../backend:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - tienda-d-db
      - tienda-d-web

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - backend
    entrypoint: ['composer', '--ignore-platform-reqs'] # Install without other php modules required

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - tienda-d-db

networks:
  tienda-d-db:
  tienda-d-web:
